Add LAVA

diff --git a/dev-util/lava-server/files/postinst b/dev-util/lava-server/files/postinst
--- a/dev-util/lava-server/files/postinst
+++ b/dev-util/lava-server/files/postinst
@@ -1,13 +1,25 @@
+#!/bin/sh
+
+die() {
+	echo "$@"
+	exit 1
+}
+
+cd /
+export LANG=C
+export LC_ALL=C
+locale
+
 . /etc/lava-server/instance.conf
 # Create database user, if it doesn't exist
     if ! su postgres -c "psql \"-c SELECT usename FROM pg_user WHERE usename='$LAVA_DB_USER'\"" | grep "$LAVA_DB_USER"; then
-        su postgres -c "createuser --no-createdb --encrypted --login --no-superuser --no-createrole --no-password --port $LAVA_DB_PORT $LAVA_DB_USER"|| "Failed to create database user"
+        su postgres -c "createuser --no-createdb --encrypted --login --no-superuser --no-createrole --no-password --port $LAVA_DB_PORT $LAVA_DB_USER"|| die "Failed to create database user"
         # Set a password for our new user
         su postgres -c "psql --port $LAVA_DB_PORT --quiet --command=\"ALTER USER \"$LAVA_DB_USER\" WITH PASSWORD '$LAVA_DB_PASSWORD'\"" || die "Failed to set database password"
     fi
     # Create a database for our new user, if it doesn't exist
     if ! su postgres -c "psql -c \"SELECT datname FROM pg_database WHERE datname='$LAVA_DB_NAME'\"" | grep "$LAVA_DB_NAME"; then
-        su postgres -c "createdb --port $LAVA_DB_PORT --locale=C.UTF-8 --encoding=UTF-8 --owner=$LAVA_DB_USER --template=template0 --no-password $LAVA_DB_NAME" || die "Failed to create a database"
+        su postgres -c "createdb --port $LAVA_DB_PORT --locale=C --encoding=UTF-8 --owner=$LAVA_DB_USER --template=template0 --no-password $LAVA_DB_NAME" || die "Failed to create a database"
     fi
     # Create devel user, if it doesn't exist, for unit test support
 #    if ! su postgres -c "psql \"-c SELECT usename FROM pg_user WHERE usename='devel'\"" | grep "devel"; then
